version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - ${MYSQL_PORT}
    volumes:
      - data_volume:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
  minio:
    image: quay.io/minio/minio:RELEASE.2024-02-26T09-33-48Z
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
      MINIO_ADDRESS: :9000
      MINIO_CONSOLE_ADDRESS: :9001
    command: server /data
volumes:
  data_volume:
