logging:
  org:
    hibernate:
      SQL: debug
snapadmin:
  enabled: true
sentry:
  dsn: ${SENTRY_DSN}
  environment: dev
  enable-tracing: true
  traces-sample-rate: 1.0
  debug: false
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: debug
