spring:
  profiles:
    active: local
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_URL}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: ${java.io.tmpdir}
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY_ID}
        secretKey: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_IMAGE_BUCKET}
        endpoint: ${AWS_S3_IMAGE_ENDPOINT}
        path-style-access-enabled: true
jwt:
  issuer: ${TOKEN_ISSUER}
  base64-secret: ${TOKEN_SECRET}
  access-token-validity-in-seconds: ${ACCESS_TOKEN_EXPIRATION}
  refresh-token-validity-in-seconds: ${REFRESH_TOKEN_EXPIRATION}
server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework
cors:
  service-origin: ${SERVICE_ORIGIN}
springdoc:
  swagger-ui:
    path: /docs
    filter: true
snapadmin:
  baseUrl: admin-panel
  modelsPackage: team.silvertown.masil
  sql-console-enabled: false
sentry:
  dsn: ${SENTRY_DSN}
