logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
    root: info
spring:
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
