logging:
  org:
    hibernate:
      SQL: debug
  threshold:
    file: ERROR
  file:
    name: logs/masil.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/ddudu.%d{yyyy-MM-dd}.%i.log
      max-file-size: 1MB
      total-size-cap: 5MB
springdoc:
  swagger-ui:
    enabled: false
sentry:
  dsn: ${SENTRY_DSN}
  environment: prod
  enable-tracing: true
  traces-sample-rate: 1.0
  debug: false
  logging:
    minimum-event-level: error
